name: flutter_vision
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
    - assets/images/
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/core/config/intl
  output_dir: lib/core/config/intl

  flutter_launcher_icons: null
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_round.png"
  adaptive_icon_background: "assets/icon/icon_background.png"
  min_sdk_android: 21
